# example values

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: http://radiomv.ru
      name: Radimov
    - url: https://ipfran.ru
      name: ipfran
    - url: https://dimonvideo.ru
      name: dimonvideo
    - url: https://nikoartgallery.com
      name: nikoargallery
    - url: https://et-cetera.ru/mobile
      name: et-catera
    - url: https://www.lutherancathedral.ru
      name: lutherancathedral
    - url: https://dombulgakova.ru
      name: dombulgakova
    - url: https://www.svetlovka.ru
      name: svetlovka

server:
  port: 8080
spring:
  datasource:
    username: root
    password: 603429Daxter
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
